CREATE TYPE "UserPlan" AS ENUM ('FREE', 'PRO', 'AGENCY');

ALTER TABLE "User"
ADD COLUMN "plan" "UserPlan" NOT NULL DEFAULT 'FREE',
ADD COLUMN "monthlyReviewDraftsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "monthlyHealthReportsUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "monthlyRealWritesUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "usageResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Shop"
ADD COLUMN "allowRealReplyTest" BOOLEAN NOT NULL DEFAULT false;
