ALTER TABLE "Product"
ADD COLUMN "description" TEXT,
ADD COLUMN "attributesJson" JSONB;

ALTER TABLE "AiReport"
ADD COLUMN "detailsJson" JSONB;

ALTER TABLE "TelegramIntegration"
ADD COLUMN "dailyAlertsEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "alertHour" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN "lastAlertSentAt" TIMESTAMP(3),
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
