export const SAFE_ACTIONS = new Set([
  "CREATE_REVIEW_DRAFT",
  "CREATE_SEO_DRAFT",
  "SEND_TELEGRAM_ALERT"
]);

export const DANGEROUS_ACTIONS = new Set([
  "UPDATE_PRICE",
  "UPDATE_STOCK",
  "REPLY_REVIEW",
  "UPDATE_PRODUCT_CONTENT",
  "UPDATE_AD_BID"
]);
